"""What the reset line picks up from its new neighbour on the ribbon.

    python3 tb_rst_neighbour.py            (from sim/; ngspice; seconds; writes results/rst_neighbour.md)

With the bus header on the front RST (pin 7) had a ground conductor on both sides (D017). On the back the two pins of every
pair change places (D059, D062): RST is pin 8, between a ground (7) and BUS1# (9). Reset is the one line that is not sampled
on a clock edge: every card clears on its level, so a bump that reaches a transistor's threshold is a reset. BUS1# falls fast
(a transistor pulls it) and rises slowly (the hub's 10k into every gate and the cable); the rise pushes RST up.

The bench is the two lines and what hangs on them, counted on the routed boards' own netlists: every gate and every drain on
BUS1# (a gate as a transistor with its pull-up, an idle drain as a transistor held off), the hub's 10k, the cable to ground;
on RST the panel's 10k pull-down, every card's reset input as a transistor of the low-threshold corner (Vto 0.8 V, the
datasheet's minimum) with its 47k, the cable, and the coupling to BUS1#. The clock card drives RST through a diode and is
not there while RST is low. Swept: the coupling (250, 350, 500 pF: 5 to 7 m of ribbon at 35 to 70 pF/m between neighbours)
and a capacitor from RST to ground at the hub (none, 1, 2.2, 4.7, 10 nF), with what that capacitor does to the release of
reset (the time RST takes from 3.5 V to 0.8 V through the 10k, which is the window the reset sweep is about)."""
import os, re, subprocess, glob, collections
HERE=os.path.dirname(os.path.abspath(__file__)); LIB=os.path.join(HERE,'..','lib','2N7000.lib'); OUT=os.path.join(HERE,'out'); K='/Applications/KiCad/KiCad.app/Contents/MacOS/kicad-cli'
COPIES={'memslot':8,'prog':20}; MACHINE=['alu0','alu1','alu2','alu3','clock','ctr0','ctr1','ctr2','ctr3','ctr4','ctr5','ctr6','ctr7','hub','memctl','memslot','panela','panelb','panelc','prog','reg0','reg1','reg2','reg3']
CABLE_PF=500

def count():
    """Gates and drains on RST and BUS1# over the machine, from the kicad-cli exports of the routed boards."""
    c=collections.Counter()
    for n in MACHINE+['sequencer']:
        sch=os.path.join(HERE,'..','boards','03-sequencer','sequencer.kicad_sch') if n=='sequencer' else os.path.join(HERE,'..','cards',n,f'{n}.kicad_sch')
        cir=os.path.join(OUT,f'rstn_{n}.cir'); subprocess.run([K,'sch','export','netlist','--format','spice','-o',cir,sch],capture_output=True)
        for l in open(cir):
            t=l.split()
            if t and t[0].startswith('MQ') and len(t)>=5:
                for sig in ('RST','BUS1#'):
                    if t[2]==sig: c[sig,'gate']+=COPIES.get(n,1)
                    if t[1]==sig: c[sig,'drain']+=COPIES.get(n,1)
        os.remove(cir)
    return c

def run(c,cm,guard):
    ng,nd,nr=c['BUS1#','gate'],c['BUS1#','drain'],c['RST','gate']
    deck=f"""* RST and its ribbon neighbour BUS1#
.include {LIB}
V5 vdd 0 5
Rpu vdd bus1 10k
Cb bus1 0 {CABLE_PF}p
Mg gl bus1 0 2N7000 m={ng}
Rgl vdd gl {47000/ng:.0f}
Md bus1 0 0 2N7000 m={nd-1}
Mdrv bus1 g 0 2N7000
Rg vdd g 47k
Mpre g in 0 2N7000
Vin in 0 PULSE(0 5 100u 1u 1u 400u 1000u)
Rpd rst 0 10k
Crg rst 0 {cm+100}p
Cguard rst 0 {guard}p
Cm rst bus1 {cm}p
Mr rstn rst 0 2N7000_LO m={nr}
Rl vdd rstn {47000/nr:.0f}
* the release of reset with the same load: a second RST line let go from 3.96 V
Rpd2 rst2 0 10k
C2 rst2 0 {cm*2+100+guard+nr*55}p
.ic v(rst2)=3.96
.tran 0.2u 900u uic
.control
run
meas tran up MAX v(rst) from=50u to=900u
meas tran down MIN v(rst) from=50u to=900u
meas tran card MIN v(rstn) from=50u to=900u
meas tran rise TRIG v(bus1) VAL=0.5 RISE=1 TARG v(bus1) VAL=4.5 RISE=1
meas tran release TRIG v(rst2) VAL=3.5 FALL=1 TARG v(rst2) VAL=0.8 FALL=1
quit
.endc
.end
"""
    p=os.path.join(OUT,'rst_neighbour.cir'); open(p,'w').write(deck)
    r=subprocess.run(['ngspice','-b',p],capture_output=True,text=True).stdout
    m={k:float(v) for k,v in re.findall(r'^(up|down|card|rise|release)\s*=\s*([-+.\deE]+)',r,re.M)}
    if len(m)<5: raise SystemExit(r[-2000:])
    return m

if __name__=='__main__':
    os.makedirs(OUT,exist_ok=True); c=count()
    rows=[(cm,g,run(c,cm,g)) for cm in (250,350,500) for g in (0,1000,2200,4700,10000)]
    L=["# The reset line and its new neighbour on the ribbon","",
       "Generated by `sim/tb_rst_neighbour.py` (ngspice, the transistor models of `lib/2N7000.lib`). With the bus header on the back (D059) RST is pin 8, between ground (7) and BUS1# (9); on the front it had ground on both sides.","",
       f"On the routed boards BUS1# has {c['BUS1#','gate']} gates and {c['BUS1#','drain']} drains, RST has {c['RST','gate']} card inputs; the hub pulls BUS1# up with 10k, panel A pulls RST down with 10k; {CABLE_PF} pF of cable on each line.","",
       "| Coupling RST to BUS1# | Capacitor RST to GND at the hub | RST rises to | RST falls to | A card's reset input stage (Vto 0.8 V, 47k) dips to | BUS1# rises in | Reset releases in (3.5 V to 0.8 V) |","|---|---|---|---|---|---|---|"]
    for cm,g,m in rows: L.append(f"| {cm} pF | {'none' if not g else f'{g/1000:g} nF'} | {m['up']:.2f} V | {m['down']:.2f} V | {m['card']:.2f} V of 5 | {m['rise']*1e6:.0f} us | {m['release']*1e6:.0f} us |")
    L+=["","The datasheet's lowest threshold is 0.8 V at 1 mA; the typical part is 2.1 V. A reset input stage that stays within a few tenths of the rail has not moved the logic behind it.",""]
    os.makedirs(os.path.join(HERE,'results'),exist_ok=True); open(os.path.join(HERE,'results','rst_neighbour.md'),'w').write('\n'.join(L))
    print('\n'.join(L))
